# Generated by Django 4.1 on 2022-08-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_submitassignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitassignments',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
