# Generated by Django 4.1 on 2022-08-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_submitassignments_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitassignments',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
